# Generated by Django 3.0 on 2024-02-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseScore',
            fields=[
                ('id_student', models.IntegerField(primary_key=True, serialize=False)),
                ('name_course', models.TextField()),
                ('college', models.TextField()),
                ('professor', models.TextField()),
                ('score', models.IntegerField()),
            ],
        ),
    ]
