# Generated by Django 3.0 on 2024-02-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Score_Search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursescore',
            name='id',
            field=models.AutoField(default='0', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coursescore',
            name='id_student',
            field=models.IntegerField(),
        ),
    ]
